# Generated by Django 4.0.4 on 2022-05-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='One_Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('View_All_products', models.URLField(blank=True, null=True)),
                ('shop_now', models.URLField(blank=True, null=True)),
                ('products', models.URLField(blank=True, null=True)),
                ('Front_pic', models.URLField(blank=True, null=True)),
                ('contact', models.URLField(blank=True, null=True)),
                ('about', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.URLField(blank=True, null=True)),
                ('buy_now_link', models.URLField(blank=True, null=True)),
                ('product_name', models.CharField(max_length=200)),
                ('product_prize', models.CharField(max_length=100)),
            ],
        ),
    ]
